FOR-469: Add character and word count components
HMPO/hmpo-components pull request #171
Opened 2024-10-25 07:58 UTC by Rhyad-Zergane-HO

* Update git ignore to ignore ds_store
* Add hmpo-text-counter as base for new word and character counter; it implements gds character counter
* Add hmpo-word-counter to count words, based on hmpo-text-counter
* Add hmpo-character-counter to count characters, based on hmpo-text-counter
* Add unit tests for each component
* Add new global function to translate extra field keys
* Add unit test for new global function

2024-10-25 10:20 UTC, georgeeker commented on components/hmpo-character-count/macro.njk
> +{% macro hmpoCharacterCount(ctx, params, base) %}
We do already have a hmpo-chars-left component - That I think effectively matches what this component is doing.

Appreciate that component wasn't using the govuk one but in my head we'd refactor that component over introducing a new separate component. (That would mean we need to test that components current uses i.e feedback-submit page)

2024-10-25 10:25 UTC, georgeeker commented on components/hmpo-word-count/macro.njk
> +{% macro hmpoWordCount(ctx, params, base) %}
Honestly I don't really think there's a need to expose this as hmpoWordCount / hmpoCharacterCount - I don't see why we don't just expose the text-count that you've added and then the consuming app can just pass in type: wordcount/charactercount

2024-10-25 10:41 UTC, georgeeker commented on components/hmpo-word-count/macro.njk
> +{% macro hmpoWordCount(ctx, params, base) %}
That's fair enough

2024-10-25 10:48 UTC, georgeeker commented on components/hmpo-character-count/macro.njk
> +{% macro hmpoCharacterCount(ctx, params, base) %}
Yeah my thoughts on this are I think that we created the charsLeft before GDS had a component at all and now by having 2 components doing v similar things we're introducing a lack of consistency. 

At the very least I think we should be creating a debt stories to refactor these together and review changing feedback to new components.

2024-10-25 12:53 UTC, msjhall138 approved these changes

2024-10-25 12:59 UTC, matthewdoreilly reviewed
Looks good. Just one spelling mistake

2024-10-25 12:59 UTC, matthewdoreilly commented on README.md
> +hmpoCharcaterCount will be replacing hmpoCharsLeft however for backwards compatability it will still be remaining. When using hmpoCharacterCount you will need specify a maxlength validator for the co
"hmpoCharcaterCount" -> "hmpoCharacterCount"

2024-10-25 13:03 UTC, ChrisThompsonK commented on components/hmpo-character-count/spec.macro.js
> +        expect($hint.text().trim()).to.equal('[fields.my-input.hint]');
Could we restructure the tests a bit? 

Logic looks good to me but I think the format could be better. See example below

```
const $ = render({ component: 'hmpoCharacterCount', params: { id: 'my-input' }, ctx: true }, locals);
const $hint = $('.govuk-hint');
const $label = $('.govuk-label');

expect($label.text().trim()).to.equal('[fields.my-input.label]');
expect($label.attr('id')).to.equal('my-input-label');
expect($hint.text().trim()).to.equal('[fields.my-input.hint]');
```

2024-10-28 09:05 UTC, matthewdoreilly approved these changes

2024-10-28 09:55 UTC, SamChatfield requested changes

2024-10-28 09:55 UTC, SamChatfield commented on README.md
> +hmpoCharacterCount(ctx, params)
Should be in `Available form wizard components` rather than here I think, that's about actual form fields it looks like

2024-10-28 09:55 UTC, SamChatfield commented on README.md
> +hmpoWordCount(ctx,params)
Similar for this

2024-10-28 09:55 UTC, SamChatfield commented on README.md
> +hmpoCharacterCount
`hmpoCharacterCount(ctx, params)` seems like it's the usage

2024-10-28 09:58 UTC, SamChatfield commented on components/hmpo-character-count/macro.njk
> +{% macro hmpoCharacterCount(ctx, params, base) %}
We'd need to add these new fields to [hmpo-field](https://github.com/HMPO/hmpo-components/blob/master/components/hmpo-field/macro.njk) to allow them to be auto-rendered on `form-template` pages

2024-10-28 10:00 UTC, SamChatfield commented on eslint.config.js
> +    },
Duplicate from rebase

2024-10-28 10:00 UTC, SamChatfield commented on package-lock.json
> -      "license": "MIT",
Can possibly roll this back if it was a merge-conflict thing on rebase

2024-10-28 10:31 UTC, SamChatfield approved these changes
LGTM

2024-10-28 11:45 UTC, georgeeker approved these changes

2024-10-28 12:34 UTC, BecioProton approved these changes

2024-10-28 12:34 UTC, merged